### ISSUE TITLE
`libhl.so` issue does not seem to be fixed

### ISSUE THREAD

**Issue by CedX** [PXshadow/setup-hashlink#1]
I still encounter this error:

```
hl: error while loading shared libraries: libhl.so: cannot open shared object file: No such file or directory
```

Haxe 4.2.4 on Ubuntu 20.04.3, with `setup-hashlink@master`
(see https://github.com/cedx/which.hx/runs/4049345363?check_suite_focus=true)

**Comment by CedX** [comment]
Weird... this action uses the latest Git commit from HashLink to compile the Linux sources. If I explicitly use the sources from the `1.11` tag, everything works as expected. I'm not sure but I suspect that this issue is more related to HashLink than to this action. On the basis of this assumption and [this line](https://github.com/PXshadow/setup-hashlink/blob/master/Main.hx#L24), I close the issue.

**Comment by PXshadow** [comment]
That is strange @cedx sorry for not getting to you sooner, I saw your new setup-hashlink happy to link to that for this repo, does it have the hdlls working yet?

**Comment by cedx** [comment]
Sorry for the delay: I'm currently very busy 😢
I started by forking your project... and things gone out of control! As you have probably noticed, I have completely rewritten the project. I really wanted to have something predictible (i.e. using your project, we get a different version of HashLink depending on the target platform).

> does it have the hdlls working yet?

I'm not really sure: my tests with HashLink are pretty limited. I use it on my projects,

**Comment by CedX** [comment]
Sorry for the delay: I'm currently VERY busy 😢

I started by forking your project... and things gone out of control! As you have probably noticed, I have completely rewritten the project. I really wanted to have something predictible (i.e. using your project, we get a different version of HashLink depending on the target platform).

> Does it have the hdlls working yet?

I'm not really sure: my tests with HashLink are pretty limited. I use it on my projects (which are very basic), just to see if they are compatible. I don't use OpenAL, SDL, etc. So, I'm waiting for the feedback from the community to know if everything is OK or not. I guess not everything works perfectly. Especially since HashLink really seems to be a Windows project more than anything else (i.e. [there are still a lot of compilation errors on MacOS](https://github.com/cedx/setup-hashlink/runs/4188931369)).
